/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/dialogs/Alert.vue')['default']
    copy: typeof import('./src/components/dialogs/EditQuestionSheet copy.vue')['default']
    CreateQuestionSheet: typeof import('./src/components/dialogs/CreateQuestionSheet.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    Dropdown: typeof import('./src/components/dropdown.vue')['default']
    DropdownMenuContent: typeof import('radix-vue')['DropdownMenuContent']
    DropdownMenuItem: typeof import('radix-vue')['DropdownMenuItem']
    DropdownMenuPortal: typeof import('radix-vue')['DropdownMenuPortal']
    DropdownMenuRoot: typeof import('radix-vue')['DropdownMenuRoot']
    DropdownMenuTrigger: typeof import('radix-vue')['DropdownMenuTrigger']
    EditQuestionSheet: typeof import('./src/components/dialogs/EditQuestionSheet.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PreviewQuestionSheet: typeof import('./src/components/dialogs/PreviewQuestionSheet.vue')['default']
    QuestionSheet: typeof import('./src/components/dialogs/QuestionSheet.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectContent: typeof import('radix-vue')['SelectContent']
    SelectItem: typeof import('radix-vue')['SelectItem']
    SelectItemText: typeof import('radix-vue')['SelectItemText']
    SelectPortal: typeof import('radix-vue')['SelectPortal']
    SelectRoot: typeof import('radix-vue')['SelectRoot']
    SelectTrigger: typeof import('radix-vue')['SelectTrigger']
    SelectValue: typeof import('radix-vue')['SelectValue']
    SelectViewport: typeof import('radix-vue')['SelectViewport']
    SendModel: typeof import('./src/components/SendModel.vue')['default']
    SidebarComponent: typeof import('./src/components/SidebarComponent.vue')['default']
    Toast: typeof import('./src/components/toast.vue')['default']
    Toaster: typeof import('./src/components/Toaster.vue')['default']
    ToastProvider: typeof import('radix-vue')['ToastProvider']
  }
}
